### PR TITLE
Fix tar handler to not break on truncated archives

### LINKED ISSUE #156: Truncated TAR archive fails to extract
Related to #118 and can be seen on files contained in the referenced firmware.

A file containing partial TAR archive fails to extract with:
```
Traceback (most recent call last):
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/finder.py", line 81, in search_chunks_by_priority
    chunk = handler.calculate_chunk(limited_reader, real_offset)
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/handlers/archive/tar.py", line 100, in calculate_chunk
    end_offset = _get_tar_end_offset(file)
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/handlers/archive/tar.py", line 20, in _get_tar_end_offset
    last_offset = _get_end_of_last_tar_entry(file)
  File "/home/vlaci/devel/git/github.com/IoT-Inspector/unblob/unblob/handlers/archive/tar.py", line 28, in _get_end_of_last_tar_entry
    last_member = tf.getmembers()[-1]
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/tarfile.py", line 1799, in getmembers
    self._load()        # all members, we first have to
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/tarfile.py", line 2397, in _load
    tarinfo = self.next()
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/tarfile.py", line 2321, in next
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data
```
If there are multiple records in the file, it makes sense to just rewind to the last non-corrupt one.

### PR DESCRIPTION
**Pull request by QKaiser**
Fix #156 by rewinding to the last non-corrupt one. `TarFile.members` attribute is filled by calling `TarFile.next()` when we call `TarFile.getmembers()`.

We can catch the `ReadError` and the members list will contain all the archive entries that were properly parsed prior to the exception being raised on the corrupt/truncated one.

### CODE REVIEW

**Comment by QKaiser** [comment]
This fix is incomplete, do not merge yet. See https://github.com/IoT-Inspector/unblob/issues/156#issuecomment-1017802213

**Comment by QKaiser** [comment]
> This fix is incomplete, do not merge yet. See [#156 (comment)](https://github.com/IoT-Inspector/unblob/issues/156#issuecomment-1017802213)

Ok to be reviewed now.

**Comment by vlaci** [comment]
I forgot, I wanted to add some tests for these cases. I'll do it tomorrow

**Comment by vlaci** [comment]
Something is fishy: https://github.com/IoT-Inspector/unblob/pull/198

**Pull request merged**
